#!/bin/bash
set -e -u -o pipefail

# Configure known hosts
echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >>/etc/ssh/ssh_known_hosts

# Configure ssh authentication
if [ -n "${SSH_KEY:-}" ] || [ -n "${SSH_KEY_VAR:-}" ]; then
    eval "$(ssh-agent -s)" >/dev/null
    mkfifo -m 600 ~/.ssh_key.fifo && printf -- "${!SSH_KEY_VAR:-"$SSH_KEY"}\n" >~/.ssh_key.fifo | ssh-add ~/.ssh_key.fifo && rm ~/.ssh_key.fifo
fi

# Configure Git user
if [ -n "${GITHUB_TOKEN:-}" ]; then
    gh_actor_profile="$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/users/${GITHUB_ACTOR}")"
    git config --global user.name "$(printf '%s' "$gh_actor_profile" | jq -r .name)"
    git config --global user.email "$(printf '%s' "$gh_actor_profile" | jq -r .email)"
fi

# Run command
"$@"
